# Kubernetes CheCluster patch for Eclipse Che Server (TypeScript)
#
# Usage with chectl:
# IMPORTANT: chectl does NOT run envsubst on this file.
# So for chectl usage, keep a concrete image value below.
#   chectl server:deploy --platform=openshift --batch --che-operator-cr-patch-yaml=$(PWD)/cr-patch.yaml
#   chectl server:update --che-operator-cr-patch-yaml=$(PWD)/cr-patch.yaml
#
# Usage with kubectl (if you WANT env vars):
#   export IMAGE_REGISTRY_HOST=docker.io
#   export IMAGE_REGISTRY_USER_NAME=your-username
#   export IMAGE_TAG=next
#   envsubst < cr-patch.yaml | kubectl apply -n eclipse-che -f -
#
# Or use the patch script:
#   export IMAGE_REGISTRY_HOST=docker.io
#   export IMAGE_REGISTRY_USER_NAME=your-username
#   ./run/patch.sh
#
# Default image (when not using envsubst):
#   docker.io/olexii4dockerid/che-server:next
#
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  components:
    cheServer:
      deployment:
        containers:
          # Concrete image value (works with chectl):
          - image: 'docker.io/olexii4dockerid/che-server:next'
            imagePullPolicy: Always
            name: che-server
