### Copyright (c) 2025 Red Hat, Inc.
### This program and the accompanying materials are made
### available under the terms of the Eclipse Public License 2.0
### which is available at https://www.eclipse.org/legal/epl-2.0/
###
### SPDX-License-Identifier: EPL-2.0
###
### Contributors:
###   Red Hat, Inc. - initial API and implementation
###
### Factory Resolver Examples
### Demonstrates the fixed devfile URL handling
###

@baseUrl = http://localhost:8080/api
### Token for Authorization header.
### Recommended for local testing: use che-server "test Bearer" format: <userid>:<username>
###   Example: user123:johndoe
###
### If you want to test with a real OpenShift user token, run `oc whoami -t` in your shell and
### paste the resulting token value here (command substitution like $(...) is not supported in .http files).
@token = user123:johndoe

### Example 1: GitHub Repository URL (NEW - Now Works!)
# Before fix: Required full URL like https://github.com/user/repo/blob/main/devfile.yaml
# After fix: Automatically tries devfile.yaml and .devfile.yaml
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://github.com/eclipse/che"
}

### Example 2: GitHub Repository with Branch
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://github.com/eclipse/che/tree/main"
}

### Example 3: GitHub Repository with .git suffix
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://github.com/eclipse/che.git"
}

### Example 4: GitLab Repository URL (NEW - Now Works!)
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://gitlab.com/gitlab-org/gitlab"
}

### Example 5: GitLab with Subgroups
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://gitlab.com/group/subgroup/project"
}

### Example 6: Direct Devfile URL (Backward Compatible)
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://raw.githubusercontent.com/eclipse/che/main/devfile.yaml"
}

### Example 7: Direct Devfile URL with .devfile.yaml
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://raw.githubusercontent.com/eclipse/che/main/.devfile.yaml"
}

### Example 8: GitHub with Pull Request (if supported)
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://github.com/eclipse/che/pull/123"
}

### Example 9: Bitbucket Repository URL
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://bitbucket.org/workspace/repository"
}

### Example 10: Invalid URL (Should provide helpful error)
POST {{baseUrl}}/factory/resolver
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://example.com/not-a-scm-url"
}

###
# Variables
# - baseUrl defaults to localhost che-server (/api)
# - token uses the che-server "test Bearer" format: <userid>:<username>

